-- Todo Lists table
CREATE TABLE IF NOT EXISTS todo_lists (
    id INT AUTO_INCREMENT PRIMARY KEY,
    text TEXT NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    assignee VARCHAR(255),
    priority ENUM('low', 'medium', 'high') DEFAULT 'medium',
    due_date DATE,
    category VARCHAR(255),
    company_id INT,
    user_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_company_id (company_id),
    INDEX idx_user_id (user_id),
    INDEX idx_completed (completed),
    INDEX idx_priority (priority)
);

-- Insert initial todo list items from the user's list
INSERT INTO todo_lists (text, completed, assignee, priority, created_at, updated_at) VALUES
('JV ID PATTANI DGN HJ OSMAN - EN ABE', FALSE, 'EN ABE', 'medium', NOW(), NOW()),
('AGREEMENT CAFE PATTANI RENEW - EN ABE', FALSE, 'EN ABE', 'medium', NOW(), NOW()),
('BAYARAN MAHKAMAH UZAIR - TEAM KEW', FALSE, 'TEAM KEW', 'high', NOW(), NOW()),
('ENZA - PERANCANGAN2 DI M2, M3, SWK - ENZA', FALSE, 'ENZA', 'medium', NOW(), NOW()),
('JOIN ORG LUAR UTK PGRM2 BERSAMA - TEAM ZM', FALSE, 'TEAM ZM', 'medium', NOW(), NOW()),
('TUTUP ANAK SYARIKAT GISBH YG DORMANT - EKO', FALSE, 'EKO', 'high', NOW(), NOW()),
('BAS PADA CENDANA AUTO. KIRA2 NYA MCMN - TN AMIN', FALSE, 'TN AMIN', 'medium', NOW(), NOW()),
('KELAB PAYUNG PUTERI - RPUM', FALSE, 'RPUM', 'low', NOW(), NOW()),
('KHUTBAH. UTK SELATAN THAI JUGA - TN MAARUF', FALSE, 'TN MAARUF', 'medium', NOW(), NOW()),
('TEAM UTK HADIRI SEMINAR - TEAM ZM', FALSE, 'TEAM ZM', 'medium', NOW(), NOW()),
('TRM. JUMPA DA. BANGUNKN TRM DGN PPZ - EKO DAN TEAM ZM', FALSE, 'EKO, TEAM ZM', 'medium', NOW(), NOW()),
('LAPORAN MINGGUAN TTG RIFAAH A - EKA', FALSE, 'EKA', 'medium', NOW(), NOW()),
('OTP GERAKKAN - TEAM OTP', FALSE, 'TEAM OTP', 'high', NOW(), NOW()),
('INFO ENZA DI SWK, M2 - ENZA', FALSE, 'ENZA', 'low', NOW(), NOW()),
('FOLLOW HJ SALLEH @TNH - TNH', FALSE, 'TNH', 'medium', NOW(), NOW()),
('PROPOSAL LENGKAP UTK SYED HOOD - EN ZAR', FALSE, 'EN ZAR', 'high', NOW(), NOW()),
('SELESAIKAN URUSAN UTK JUAL TANAH BT HAMPAR - TN QUDAMAH', FALSE, 'TN QUDAMAH', 'high', NOW(), NOW()),
('TERUSKAN PERHUBUNGAN DGN AISYAH BAICON DLL - TNH', FALSE, 'TNH', 'medium', NOW(), NOW()),
('SEWAAN TANAH RND ENZA BIOTECH - EKA', FALSE, 'EKA', 'medium', NOW(), NOW()),
('BANGUNKAN TRM - TEAM ZM', FALSE, 'TEAM ZM', 'medium', NOW(), NOW()),
('SELESAIKAN HUTANG MART DENGAN KASIH SAYANG - EN ALI HASSAN', FALSE, 'EN ALI HASSAN', 'high', NOW(), NOW()),
('KEM MTVSI BUKA PADA ORG LUAR - APS', FALSE, 'APS', 'medium', NOW(), NOW()),
('KHUTBAH UTK MASYARAKAT - APS', FALSE, 'APS', 'medium', NOW(), NOW()),
('KEMPEN SERTAI PERSATUAN2 LUAR - TEAM ZM', FALSE, 'TEAM ZM', 'medium', NOW(), NOW()),
('MAAL HIJRAH. JOIN GROUP LUAR - TEAM ZM', FALSE, 'TEAM ZM', 'medium', NOW(), NOW()),
('EXPO BANGKOK - EN ABE', FALSE, 'EN ABE', 'medium', NOW(), NOW()),
('FOLLOW UP AMLA ASET DISITA - TEAM AMLA', FALSE, 'TEAM AMLA', 'high', NOW(), NOW()),
('JUMPA TN TAR DAN ZAIM TUNTUT BRG² DR PDRM - EKO', FALSE, 'EKO', 'high', NOW(), NOW()),
('OTP UTK M2. BUAT MAPPING MAQLUBAH. UTK FOKUS TINDAKAN2 - TEAM M2', FALSE, 'TEAM M2', 'high', NOW(), NOW()),
('SEMAK SEMULA PENDIDIKAN DI M2 - TEAM M2', FALSE, 'TEAM M2', 'medium', NOW(), NOW()),
('MANIFESTO. MELALUI JAWAPAN2 KPD PERMASALAHAN POLITIK, DGN MINDA2 M. HALATUJU KITA MELALUI MINDA, PERJUANGAN M. SUPPORTED DGN QURAN HADIS. - TEAM MANIFESTO', FALSE, 'TEAM MANIFESTO', 'high', NOW(), NOW()),
('WUJUDKAN SATU PROJEK CONTOH DALM 2 BULAN. BY 22 JULAI. PROJEK TANAH JERAM. ASAIMEN IKUT KATEGORI. - TNF DAN ZM', FALSE, 'TNF, ZM', 'high', NOW(), NOW()),
('PN HAILA (CHINA). PENGAJIAN, SUASANA ISLAM DI MSIA. JUMPA KOMUNITI MRK - AZHAR CHEN (?). SIAPA KWN2 MRK DI MSIA. - PKA, TSCKA', FALSE, 'PKA, TSCKA', 'medium', NOW(), NOW()),
('JUMPA FATEH RAZAK, DEHYA RAHMAN - 4MAT', FALSE, '4MAT', 'medium', NOW(), NOW()),
('TANAH DM - F UP SURAT AGREEMENT. HNTAR DRAFT NYA KPD DM. - TAS', FALSE, 'TAS', 'high', NOW(), NOW()),
('TANAH JERAM - PERNIAGAAN OK. JETI - STUDY LEGAL. PENGURUSAN PROJEK JERAM - TNF', FALSE, 'TNF', 'high', NOW(), NOW()),
('BMW UTK DA. LEPAS OK.. BERGANTUNG NILAI DA NAK AMBIK - TWS', FALSE, 'TWS', 'medium', NOW(), NOW()),
('JUMPA DR FAUZI - TAAAR THAH', FALSE, 'TAAAR, THAH', 'medium', NOW(), NOW()),
('KIFFAH TRAVEL. CARI INFO - TN HANZALAH', FALSE, 'TN HANZALAH', 'low', NOW(), NOW()),
('ASET BOSNIA - JUMPA EN NORMAN', FALSE, 'EN NORMAN', 'medium', NOW(), NOW()),
('TANAH RND ENZA BIOTECH - EKA', FALSE, 'EKA', 'medium', NOW(), NOW()),
('LAPORAN BULANAN PREMIS, PROJEK - TEAM ZM', FALSE, 'TEAM ZM', 'medium', NOW(), NOW()),
('SISTEM TERNAKAN AYAM - EJI', FALSE, 'EJI', 'medium', NOW(), NOW()),
('KAFE QAHWA - TSCKA, PKA', FALSE, 'TSCKA, PKA', 'medium', NOW(), NOW()),
('TEAM DI M2 PERKEMASKAN - TEAM M2', FALSE, 'TEAM M2', 'medium', NOW(), NOW()),
('NAMA2 KE UMRAH - TEAM', FALSE, 'TEAM', 'low', NOW(), NOW()),
('MODULAR GORO RM8K. - TEAM ZM', FALSE, 'TEAM ZM', 'medium', NOW(), NOW()),
('DR FAUZI. BERGABUNG DGN PENDIDIKAN - APS', FALSE, 'APS', 'medium', NOW(), NOW()),
('HJ MISWAN. PROJEK JAHITAN. - SYARIKAT JAHITAN', FALSE, 'SYARIKAT JAHITAN', 'medium', NOW(), NOW()),
('JUAL LOT DB BHC. AKHIE HUANG - EKO', FALSE, 'EKO', 'high', NOW(), NOW()),
('TANAH SP. MAHKAMAH. - EKO', FALSE, 'EKO', 'high', NOW(), NOW()),
('AMBIL ALIH TANAH BENTONG. - EKO', FALSE, 'EKO', 'high', NOW(), NOW()),
('TANAH JELEBU BANGUNKAN', FALSE, '', 'medium', NOW(), NOW()),
('TANAH LABU LANJUT DA', FALSE, '', 'medium', NOW(), NOW()),
('TANAH REMBAU DATO UJAT', FALSE, '', 'medium', NOW(), NOW()),
('PROJEK TAUGEH - THMN', FALSE, 'THMN', 'medium', NOW(), NOW()),
('TANAH MERLIMAU - TAAAR', FALSE, 'TAAAR', 'medium', NOW(), NOW()),
('EQUINE A TO Z - TAA', FALSE, 'TAA', 'medium', NOW(), NOW()),
('SEWA BANGUNAN EVENT MGT - PKA', FALSE, 'PKA', 'medium', NOW(), NOW()),
('SEWAAN RMH DA PENANG - TSCKA', FALSE, 'TSCKA', 'medium', NOW(), NOW()),
('ARAFAH HOTEL - EN FATEH', FALSE, 'EN FATEH', 'medium', NOW(), NOW()),
('HSTAY DI NEGERI2 - TEAM', FALSE, 'TEAM', 'low', NOW(), NOW()),
('SAFINA DI M3 - EN ABE', FALSE, 'EN ABE', 'medium', NOW(), NOW()),
('EXPORT AL HADDAD - PKA, EXPORT', FALSE, 'PKA, EXPORT', 'medium', NOW(), NOW()),
('PES TOMYAM KE TURKIYE - PKA, EXPORT', FALSE, 'PKA, EXPORT', 'medium', NOW(), NOW()),
('TEAM PERHUBUNGAN - EN NIK H', FALSE, 'EN NIK H', 'medium', NOW(), NOW()),
('TIMELINE PJNGAN - TAS', FALSE, 'TAS', 'medium', NOW(), NOW()),
('BANK FITNAH - MEDIA TN ALAH', FALSE, 'TN ALAH', 'high', NOW(), NOW()),
('KULIAH MTVSI 30 TAJUK - APS', FALSE, 'APS', 'medium', NOW(), NOW()),
('JADUAL KURSUS RESOLVIA - TSCKA', FALSE, 'TSCKA', 'medium', NOW(), NOW()),
('PGRM PRISMA, KAUNSELING - TSCKA', FALSE, 'TSCKA', 'medium', NOW(), NOW()),
('BAYARAN LBDI - ALP, TEAM OZZIE', FALSE, 'ALP, TEAM OZZIE', 'high', NOW(), NOW()),
('GERAN2 KRJN - PERSATUAN2', FALSE, 'PERSATUAN2', 'medium', NOW(), NOW()),
('MAHA 2026 - PUATL', FALSE, 'PUATL', 'medium', NOW(), NOW()),
('KSAMA DGN MAIS - TAS', FALSE, 'TAS', 'medium', NOW(), NOW()),
('NAMA2 KE MEKAH UMRAH - TEAM ZM', FALSE, 'TEAM ZM', 'low', NOW(), NOW()),
('RESPON KPD KRIANSAK - TN MAARUF', FALSE, 'TN MAARUF', 'medium', NOW(), NOW()),
('PENDIDIKAN ANAK2 ANGKAT DI BKK - EN ABE', FALSE, 'EN ABE', 'medium', NOW(), NOW()),
('MART S2 - ENH', FALSE, 'ENH', 'medium', NOW(), NOW()),
('CC - THAH DAN TEAM CC', FALSE, 'THAH, TEAM CC', 'medium', NOW(), NOW()),
('JV ALHADDAD - TEAM STOKIST', FALSE, 'TEAM STOKIST', 'medium', NOW(), NOW()),
('BUKU PEMULIHAN - EN ZAR APS', FALSE, 'EN ZAR, APS', 'medium', NOW(), NOW()),
('BUKU SDAAK UTK MUTAWWIF - APS', FALSE, 'APS', 'medium', NOW(), NOW()),
('CARTA SALASILAH R - APS', FALSE, 'APS', 'low', NOW(), NOW()),
('TUISYEN IKUT PERINGKAT UMUR - APS', FALSE, 'APS', 'medium', NOW(), NOW()),
('TT MOTIVASI MINDA - APS', FALSE, 'APS', 'medium', NOW(), NOW()),
('JV DGN DATO HOOD - PENDIDIKAN', FALSE, 'PENDIDIKAN', 'medium', NOW(), NOW()),
('JV DR FAQAR - EKO, TAAAR', FALSE, 'EKO, TAAAR', 'medium', NOW(), NOW()),
('TERNAKAN AYAM BERSISTEM. - TAAAR', FALSE, 'TAAAR', 'medium', NOW(), NOW()),
('CAFE QAHWA - TSCKA', FALSE, 'TSCKA', 'medium', NOW(), NOW()),
('JV DATO UNDANG LUAK JOHOL - TFY', FALSE, 'TFY', 'medium', NOW(), NOW()),
('KILANG SABUN - 4MAT', FALSE, '4MAT', 'medium', NOW(), NOW()),
('OEM WILDANI - TNH', FALSE, 'TNH', 'medium', NOW(), NOW()),
('OEM MI KUNING HADDAD - THAH', FALSE, 'THAH', 'medium', NOW(), NOW()),
('KOPI GANTANG OEM - TNH', FALSE, 'TNH', 'medium', NOW(), NOW()),
('PERSATUAN2 - PENEGRUSI PERS', FALSE, 'PENEGRUSI PERS', 'medium', NOW(), NOW()),
('PGRM MOTOR RMJ - 4MAT', FALSE, '4MAT', 'medium', NOW(), NOW()),
('JV PKPS - MSMN.THAH', FALSE, 'MSMN, THAH', 'medium', NOW(), NOW()),
('KENDERAAN - GLS, BMW, DLL - TEAM ASET AMLA', FALSE, 'TEAM ASET AMLA', 'high', NOW(), NOW()),
('IMPORT TEPUNG TURKIYE - TN QUADAMAH', FALSE, 'TN QUADAMAH', 'medium', NOW(), NOW()),
('RMH PENDIDIKAN PERINGIT MELAKA. HJ ARSAT. - APS PENDIDIKAN', FALSE, 'APS, PENDIDIKAN', 'medium', NOW(), NOW()),
('PEMULIHAN BARBAROSSA. JUMPA MARA - MSMN, TSCKA', FALSE, 'MSMN, TSCKA', 'medium', NOW(), NOW()),
('KEM MOTIVASI HUJUNG MINGGU - APS, PENDIDIKAN', FALSE, 'APS, PENDIDIKAN', 'medium', NOW(), NOW()),
('INFAQ HARI JUMAAT - PREMIS', FALSE, 'PREMIS', 'low', NOW(), NOW()),
('TANAH UTK JEC GUNA UTK TERNAKAN - TAA', FALSE, 'TAA', 'medium', NOW(), NOW()),
('OTP M2 - TEAM M2', FALSE, 'TEAM M2', 'high', NOW(), NOW()),
('Timeline - rujuk dgn TC utk panduan maklumat bg TMT. (En Fajrul)', FALSE, 'EN FAJRUL', 'medium', NOW(), NOW()),
('Pekan Baru - sediakan alternatif tanah baru sbg perancangan awal. (Pak Darwis)', FALSE, 'PAK DARWIS', 'medium', NOW(), NOW()),
('Pgrm kpd Team YB Emiryati - boleh buat pgrm yg mrk minta, tp kena bertegas.. sbb kita nak satukan semua parti politik atas nama Islam. (En Zarnukman)', FALSE, 'EN ZARNUKMAN', 'high', NOW(), NOW()),
('Mart S2 - wibawakan premis ikut era skrg. (En Nik Hishamuddin)', FALSE, 'EN NIK HISHAMUDDIN', 'medium', NOW(), NOW()),
('Manifesto - siapkan segera. PRN PRU dah dekat. (Team Manifesto)', FALSE, 'TEAM MANIFESTO', 'high', NOW(), NOW()),
('Status Shumardijaya.. (En Wan Alisabi)', FALSE, 'EN WAN ALISABI', 'medium', NOW(), NOW()),
('Berhubung dg MARA cari lg peluang sebanyaknya - EKA', FALSE, 'EKA', 'high', NOW(), NOW()),
('Berhubung, cari maklumat ttg 5 nama yg buat report sekitar 2013 - Tn Hasnan', FALSE, 'TN HASNAN', 'medium', NOW(), NOW()),
('Tawaran Pjbt Agama Bentong.', FALSE, '', 'medium', NOW(), NOW()),
('Tn Mashdiq Ketua Jbtn KDN Sel - bantuan utk buka akaun. (THAH)', FALSE, 'THAH', 'medium', NOW(), NOW()),
('NTW - yg ada 3T boleh bercakap. Atas nama manifesto. Latih bercakap atas dasar perjuangan, dan ikut kategori2 berkenaan. (TSCKA)', FALSE, 'TSCKA', 'medium', NOW(), NOW()),
('Tambah ikuti 3T sehingga 50 org. (TSCKA)', FALSE, 'TSCKA', 'medium', NOW(), NOW()),
('Buang perangai2 buruk kita yg membawa kpd OG. Tambah kefahaman dan keyakinan. (ZM)', FALSE, 'ZM', 'high', NOW(), NOW()),
('24 Jun *Persidangan Inovasi Halal & Keterjaminan Makanan MADANI*. Cari info dan join. (TSCKA)', FALSE, 'TSCKA', 'medium', NOW(), NOW()),
('Syh Abdullah Yemeni. Import jus guava dan mangga. 200 karton. (MSMN, TNF)', FALSE, 'MSMN, TNF', 'medium', NOW(), NOW()),
('Jika ada individu yg difitnah, saman. (ZM)', FALSE, 'ZM', 'high', NOW(), NOW()),
('Contact Jajan utk pgrm2 Maal Hijrah. (ZM)', FALSE, 'ZM', 'medium', NOW(), NOW()),
('Team kewangan - legal, guna kaedah IT, strategi, konsep beli sabun, perbincangan dan rujukan. (Team Kew)', FALSE, 'TEAM KEW', 'high', NOW(), NOW()),
('JUMPA ADUN BERSATU TANYAKAN TTG PENDIRIAN BERSATU', FALSE, '', 'high', NOW(), NOW()),
('HAL PASSPORT DLL - MINTA RK URUSKAN. BERTEGAS DGN RK.', FALSE, '', 'high', NOW(), NOW()),
('SAMPAIKAN HURAIAN HADIS, MINDA, MADAH, SEJARAH, ISU SEMASA (KE DLM DIRI/ KELUARGA... DAN KE LUAR SPT MASALAH SOSIAL / POLITIK / ISU NEGARA..), DLL KAITKAN DGN PJ SEMASA. BINCANGKAN --> PROJEK EKONOMI, PENTERNAKAN, ENZA, IMPORT EXPORT, 25 SYARIKAT , (PENDIDIKAN?)', FALSE, '', 'high', NOW(), NOW()),
('ENGINEERING. BUAT TEAM. BINCANG PERANCANGAN. BAIKI DIRI, KEYAKINAN.', FALSE, '', 'high', NOW(), NOW()),
('Gabungkan hadis, minda, madah, isu semasa dll dlm memahamkan kwn2. - Team ZM', FALSE, 'TEAM ZM', 'medium', NOW(), NOW()),
('Buat mee kuning sendiri utk CFD - M2', FALSE, 'M2', 'medium', NOW(), NOW()),
('Pgrm dakwah melalui CFD - M2', FALSE, 'M2', 'medium', NOW(), NOW()),
('Tanah LBDI - cari jln penyelesaian apa yg TL blh tlg / dlm 2/3 hari - TFY, TAA, TNH', FALSE, 'TFY, TAA, TNH', 'high', NOW(), NOW()),
('Sharp shooter berperanan - TAS, EKA', FALSE, 'TAS, EKA', 'high', NOW(), NOW()),
('Perbincangan dg ust Din kena cukup maklumat hal nilaian harga bas - THAH', FALSE, 'THAH', 'medium', NOW(), NOW()),
('Kena ada perancangan kenderaan2 dibebaskan dari AMLA - FU', FALSE, 'FU', 'high', NOW(), NOW()),
('Ziarah kaum cina: target orng yg faham dan mudah faham, buat program atas nama perniagaan. Tajuk : kekeluargaan (Islam Cara Hidup) - TSCKA, PKA', FALSE, 'TSCKA, PKA', 'medium', NOW(), NOW()),
('Tanya hubungan Komuniti Cina mrk dg Daud L - supaya tk terperangkap dg anti Islam - TSCKA, PKA', FALSE, 'TSCKA, PKA', 'medium', NOW(), NOW()),
('Jaga standard motel di Jitra - TSCKA', FALSE, 'TSCKA', 'medium', NOW(), NOW()),
('DR HISHAM DI SELATAN THAI DAN SEKOLAH BT PAHAT', FALSE, '', 'medium', NOW(), NOW()),
('Jumpa Rifaah Jordan hal kenderaan', FALSE, '', 'medium', NOW(), NOW()),
('Contact Dato Nasir ... Utk repair boat²', FALSE, '', 'medium', NOW(), NOW()),
('Jual bas dan MHome. Dgn Ust Din Coaster. MH RM1j final. Cek prosedur daftar MH di M1. - Tn Hasnan', FALSE, 'TN HASNAN', 'high', NOW(), NOW()),
('GLS jual dgn Din Coaster - Tn Amin', FALSE, 'TN AMIN', 'high', NOW(), NOW()),
('Barbarossa - buatkan legal dokumen agihan share CM', FALSE, '', 'high', NOW(), NOW()),
('Persiapan di M3', FALSE, '', 'medium', NOW(), NOW()),
('Persiapan di Filipina', FALSE, '', 'medium', NOW(), NOW()),
('Maklumat kewangan', FALSE, '', 'medium', NOW(), NOW()),
('Mendoakan D. Abd Rahman Undang Luak yg sdg sakit', FALSE, '', 'low', NOW(), NOW()),
('Buat mee kuning sendiri utk CFD - dah buat di Sentul R&D cuma jumlah yg sedikit. Mee kuning Jadikan projek induk di M2 dan jadikan mee kering /sanggul/telur', FALSE, 'M2', 'medium', NOW(), NOW()),
('Indahkan MH, poolish dan baiki seblm dijual', FALSE, '', 'medium', NOW(), NOW()),
('Pastikan betul2 aset yg dh dpt serta pastikan team yg betul2 terlibat utk selesaikan', FALSE, '', 'high', NOW(), NOW()),
('Teratak Bonda - Jadikan tiga2 bangunan dr bwh ke atas sebgai tapak, buat betul2 jadikan contoh, bkn setinggan - PTB', FALSE, 'PTB', 'high', NOW(), NOW()),
('Barbarossa, berkaitan Cikgu Mahdi selesaikan secara baik.', FALSE, '', 'high', NOW(), NOW()),
('JV DGN PKPS - UBAH DASAR DAN PENDEKATAN', FALSE, '', 'high', NOW(), NOW()),
('LAPORAN KEWANGAN HARIAN SETIAP DUA HARI', FALSE, '', 'high', NOW(), NOW()),
('NAK BUAT GORO DGN IZIN.. DGN TNF', FALSE, 'TNF', 'medium', NOW(), NOW()),
('JUAL ASET2 UTK SUMBER KEWANGAN', FALSE, '', 'high', NOW(), NOW()),
('WUJUDKAN TABUNG KEBAJIKAN. KEUTAMAAN. KAYUH DAHULU..', FALSE, '', 'high', NOW(), NOW()),
('GORO SAMPAIKAN ISI ZM, BUKAN STRATEGI.. SEDIH PD YG NAK, TP TAK FAHAM..', FALSE, 'ZM', 'high', NOW(), NOW()),
('LANTIKAN KETUA BAGI NEGARA2 LUAR NEGARA DAN SELARASKAN MASA ZM', FALSE, 'ZM', 'high', NOW(), NOW()),
('SUSUN MODAL INSAN DAN MODAL KEWANGAN', FALSE, '', 'high', NOW(), NOW()),
('KENA ADA SYARIKAT LUAR NEGARA UTK TERLIBAT TERHUBUNG DGN MQBH **BINCANGKAN', FALSE, '', 'high', NOW(), NOW()),
('BANCI ANAK² SEKOLAH. BUAT TUISYEN', FALSE, '', 'medium', NOW(), NOW()),
('BOT - TERUSKN BINCG DGN DATO NASIR - THAH', FALSE, 'THAH', 'medium', NOW(), NOW()),
('UPDATE BMW ..?', FALSE, '', 'low', NOW(), NOW()),
('KARNIVAL USAHAWAN HALAL MADANI SELANGOR 2026 (B-HALAL 2026) ; SUSUN WAKIL YG BOLEH TRGKAN SITUASI KITA - ENH', FALSE, 'ENH', 'medium', NOW(), NOW()),
('PERBINCANGAN TTG PENDIDIKAN DI MESIR. ATAS NAMA SYARIKAT.. INTERVIEW MAK AYAH.. - APS, ALP, MQBH', FALSE, 'APS, ALP, MQBH', 'medium', NOW(), NOW()),
('PROJEK TERATAK BONDA BCH - PASTIKAN LOKASI, WIBAWA.', FALSE, '', 'high', NOW(), NOW()),
('SELESAIKAN HAL CM DI BARBAROSSA SECARA BAIK.', FALSE, '', 'high', NOW(), NOW()),
('JUMPA WAN JAMBI', FALSE, '', 'medium', NOW(), NOW()),
('PGRM MAK AYAH ANAK2 TVET JASIN', FALSE, '', 'medium', NOW(), NOW()),
('SELESAIKAN LDBI', FALSE, '', 'high', NOW(), NOW()),
('Manfaatkan aplikasi2 yg telah dibangunkan oleh Team IT.', FALSE, '', 'medium', NOW(), NOW()),
('Tanah RnD Enza - ambil kunci pada 1 Julai.', FALSE, '', 'high', NOW(), NOW()),
('Pjbt ENZA dan premis utk rawatan PD.', FALSE, '', 'medium', NOW(), NOW()),
('Urusan permit MHome. Buka kasut dlm MH.', FALSE, '', 'medium', NOW(), NOW()),
('Urusan Pulau Tioman. (TA, Wan Siwi, TQ). Terhubung dgn SB, Tok 4, Abg Mi. Apa tujuan..? Staf Gardenia terlibat..?', FALSE, 'TA, WAN SIWI, TQ', 'medium', NOW(), NOW()),
('Urusan kehakiman Sabah. Rayuan semakan fatwa GISBH kpd Mufti JAS.', FALSE, '', 'high', NOW(), NOW()),
('Pjbt MOBILE.. - Maqlubah, peranan ALP PZ.. sistemkan secara maya', FALSE, 'ALP, PZ', 'medium', NOW(), NOW()),
('Berunding hotel & cafe di Sarajevo. Tenok respon T smd jual atau dpt teruskan.', FALSE, '', 'medium', NOW(), NOW()),
('Kemaskan sistem pendidikan anak2', FALSE, '', 'high', NOW(), NOW()),
('Yang dh ckup umur semua kena mengundi', FALSE, '', 'high', NOW(), NOW()),
('Pendidikan kena cepat dikemaskan. Menjiwai perjuangan ini. GM dgn ibu bapa TVET. Kursus utk ibu bapa', FALSE, '', 'high', NOW(), NOW()),
('OSSEM - kembangkan cthnya buat di Putrajaya, Bangi - di tempat2 yg ramai. Ini ikatan x rasmi', FALSE, '', 'medium', NOW(), NOW()),
('Selesaikan urusan permit, cukai MH, list ini akan di masukan ke dalam company, dengan di asign companynya dengan drop down list', FALSE, '', 'high', NOW(), NOW());
