-- Insert sample member data into members table
-- Note: userId should be replaced with actual user IDs from your users table

USE maqlubah_db;

-- Get a valid user ID (assuming at least one user exists)
SET @user_id = (SELECT id FROM users LIMIT 1);

-- If no user exists, use a default ID (this should be adjusted based on your actual user data)
SET @user_id = IFNULL(@user_id, 1);

-- Insert sample members
INSERT INTO members (
  userId, 
  husband_name, 
  age, 
  phone, 
  home_address, 
  district, 
  state, 
  wives, 
  married_children, 
  unmarried_children, 
  current_job, 
  company_name, 
  struggle_understanding, 
  family_situation, 
  welfare_status, 
  five_p_activities, 
  compliance_level, 
  struggle_assessment, 
  family_management_assessment, 
  welfare_assessment, 
  five_p_assessment, 
  compliance_assessment, 
  summary, 
  status, 
  join_date, 
  last_updated,
  created_at,
  updated_at
) VALUES 
(
  @user_id,
  'Ahmad bin Ibrahim',
  42,
  '+60123456789',
  'No. 123, Jalan Utama, Taman Permai',
  'Klang',
  'Selangor',
  '["Fatimah binti Ali"]',
  2,
  3,
  'Business Owner',
  'Ahmad Enterprise',
  'Still searching for truth, believes struggle continues',
  'Children in local schools, working on self-improvement',
  'House in good condition, some debts from previous operations',
  '["Business", "Agriculture"]',
  'Good understanding of fatwa compliance',
  4,
  3,
  3,
  4,
  3,
  'Active member with good business background, working on family welfare improvement',
  'active',
  '2020-01-15',
  NOW(),
  NOW(),
  NOW()
),
(
  @user_id,
  'Mohammad bin Hassan',
  38,
  '+60123456790',
  'No. 456, Jalan Raya, Kampung Baru',
  'Kuala Lumpur',
  'Wilayah Persekutuan',
  '["Norhayati binti Ahmad"]',
  1,
  3,
  'Farmer',
  NULL,
  'Strong commitment to the struggle, believes in continuous improvement',
  'Family supportive, children progressing well in education',
  'Basic housing, working on improving living conditions',
  '["Agriculture", "Livestock"]',
  'Moderate understanding, needs more guidance',
  3,
  4,
  2,
  3,
  3,
  'Dedicated farmer with strong family values, needs support in business development',
  'active',
  '2021-02-28',
  NOW(),
  NOW(),
  NOW()
),
(
  @user_id,
  'Ismail bin Bakar',
  48,
  '+60123456793',
  'No. 654, Jalan Utama, Bandar Baru',
  'Klang',
  'Selangor',
  '["Aminah binti Rahman", "Salwah binti Ismail", "Nurul binti Hassan", "Siti binti Mohammad"]',
  5,
  3,
  'Business Owner',
  'Ismail Trading Group',
  'Very committed, strong leadership qualities',
  'Large family, managing well despite challenges',
  'Good living standards, some business-related debt',
  '["Business", "Agriculture", "Livestock"]',
  'Excellent compliance and understanding',
  5,
  4,
  4,
  5,
  5,
  'Strong leader with large family, excellent business acumen and high compliance',
  'active',
  '2017-11-15',
  NOW(),
  NOW(),
  NOW()
),
(
  @user_id,
  'Rashid bin Osman',
  35,
  '+60123456791',
  'No. 789, Jalan Perak, Ipoh Garden',
  'Ipoh',
  'Perak',
  '["Salmah binti Kassim"]',
  0,
  4,
  'Teacher',
  NULL,
  'Understanding developing, seeking more knowledge',
  'Young family, focused on children education',
  'Comfortable housing, no major issues',
  '["Business"]',
  'Good compliance, willing to learn',
  3,
  4,
  4,
  3,
  4,
  'Young professional with growing family, good potential for leadership',
  'active',
  '2022-03-10',
  NOW(),
  NOW(),
  NOW()
),
(
  @user_id,
  'Zainal bin Abidin',
  45,
  '+60123456792',
  'No. 321, Jalan Pantai, Kuala Terengganu',
  'Kuala Terengganu',
  'Terengganu',
  '["Zainab binti Sulaiman"]',
  2,
  2,
  'Fisherman',
  NULL,
  'Deeply committed, strong spiritual foundation',
  'Family well-established, children grown up',
  'Adequate housing, minimal debt',
  '["Fishing", "Agriculture"]',
  'Excellent understanding and practice',
  4,
  5,
  4,
  4,
  4,
  'Dedicated fisherman with strong family values and good compliance',
  'active',
  '2021-02-28',
  NOW(),
  NOW(),
  NOW()
);

-- Verify insertion
SELECT COUNT(*) as total_members_inserted FROM members;
